font_family      Hack Nerd Font Mono
font_size        18.0
macos_option_as_alt yes

window_padding_width 12
hide_window_decorations titlebar-only

tab_bar_style custom
tab_bar_min_tabs 1

include current-theme.conf
background_opacity 0.95
background_blur 24
